baseURL = 'https://mcu2cloud.kr/'
googleAnalytics = 'G-3EHP42VE4P'
languageCode = 'ko-kr'
title = 'Simply the Best!!!'
theme = 'PaperMod'
copyright = "© 2025 mcu2cloud.kr"

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = true

[params.giscus]
<<<<<<< HEAD
  repo = "OWNER/REPO"
  repoID = "YOUR_REPO_ID"
  category = "Announcements"
  categoryID = "YOUR_CATEGORY_ID"
  mapping = "pathname"
=======
  repo = "odise444/notes"
  repoID = "R_kgDOQjrvfg"
  category = "Announcements"
  categoryID = "DIC_kwDOQjrvfs4C0YRo"
  mapping = "pathname"
  strict = "0"
>>>>>>> 5bd6e6278202049a782b604e0b75126c2e95816a
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "ko"

[params.footer]
  text = "[About](/about/) · [개인정보처리방침](/privacy/)"

# 검색 기능을 위한 JSON 출력
[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "홈"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Techs"
  url = "/techs/"
  weight = 3

[[menu.main]]
  name = "태그"
  url = "/tags/"
  weight = 4

[[menu.main]]
  name = "검색"
  url = "/search/"
  weight = 5

[[menu.main]]
  name = "소개"
  url = "/about/"
  weight = 6
