baseURL = 'https://mcu2cloud.kr/'
googleAnalytics = 'G-3EHP42VE4P'
languageCode = 'ko-kr'
title = 'Simply the Best!!!'
theme = 'PaperMod'
copyright = "© 2025 mcu2cloud.kr"

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.footer]
  text = "[About](/about/) · [개인정보처리방침](/privacy/)"

[[menu.main]]
  name = "홈"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Techs"
  url = "/techs/"
  weight = 3

[[menu.main]]
  name = "태그"
  url = "/tags/"
  weight = 4

[[menu.main]]
  name = "검색"
  url = "/search/"
  weight = 5

[[menu.main]]
  name = "소개"
  url = "/about/"
  weight = 6
