baseURL = 'https://mcu2cloud.kr/'
languageCode = 'ko-kr'
title = 'Simply the Best!!!'
theme = 'PaperMod'

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[[menu.main]]
  name = "홈"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Techs"
  url = "/techs/"
  weight = 3

[[menu.main]]
  name = "태그"
  url = "/tags/"
  weight = 4

[[menu.main]]
  name = "검색"
  url = "/search/"
  weight = 5
