baseURL = 'https://odise444.github.io/notes/'
languageCode = 'ko-kr'
title = 'My Notes'
theme = 'PaperMod'

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[[menu.main]]
  name = "홈"
  url = "/"
  weight = 1

[[menu.main]]
  name = "글 목록"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "태그"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "검색"
  url = "/search/"
  weight = 4
